"""Static HTML report.

Deliberately a generated file rather than a served dashboard. A report that
is a single self-contained HTML file opens instantly, has no ports, no
startup race and no blank-page-while-booting failure mode -- which matters
when it is being shown live in a recorded demo. It also means a reviewer can
open the result without running our code.

No external assets: the CSS is inline and there are no scripts, so it renders
identically offline and cannot break because a CDN moved.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Optional

CSS = """
:root {
  --bg:#0f1115; --panel:#171a21; --line:#262b36; --ink:#e8eaf0;
  --muted:#9aa3b2; --good:#3fb950; --bad:#f85149; --warn:#d29922;
  --accent:#58a6ff;
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; }
.wrap { max-width:1080px; margin:0 auto; padding:40px 24px 80px; }
h1 { font-size:26px; margin:0 0 4px; letter-spacing:-.02em; }
h2 { font-size:14px; text-transform:uppercase; letter-spacing:.09em;
  color:var(--muted); margin:38px 0 14px; font-weight:600; }
.sub { color:var(--muted); margin:0 0 28px; font-size:14px; }
.caveat { background:#1d1a12; border:1px solid #4a3a12; border-left:3px solid var(--warn);
  padding:14px 18px; border-radius:8px; margin:0 0 30px; font-size:14px; }
.caveat b { color:var(--warn); }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(210px,1fr)); gap:14px; }
.card { background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:16px 18px; }
.card .label { font-size:12px; color:var(--muted); text-transform:uppercase;
  letter-spacing:.06em; margin-bottom:8px; }
.card .value { font-size:26px; font-weight:650; letter-spacing:-.02em; }
.card .note { font-size:12.5px; color:var(--muted); margin-top:7px; line-height:1.45; }
.card.hero { border-color:#2d4a6b; background:linear-gradient(180deg,#141c28,#171a21); }
.value.good { color:var(--good); } .value.bad { color:var(--bad); }
.value.muted { color:var(--muted); }
table { width:100%; border-collapse:collapse; font-size:14px;
  background:var(--panel); border:1px solid var(--line); border-radius:10px; overflow:hidden; }
th { text-align:left; font-size:11.5px; text-transform:uppercase; letter-spacing:.07em;
  color:var(--muted); padding:11px 14px; border-bottom:1px solid var(--line); font-weight:600; }
td { padding:10px 14px; border-bottom:1px solid #1e222b; }
tr:last-child td { border-bottom:none; }
td.num { text-align:right; font-variant-numeric:tabular-nums; }
.tag { font-size:11px; padding:2.5px 8px; border-radius:20px; font-weight:600;
  display:inline-block; }
.tag.yes { background:#12261a; color:var(--good); border:1px solid #1f4a2c; }
.tag.no { background:#1e1e22; color:var(--muted); border:1px solid #2c2f38; }
.bar { height:6px; background:#22262f; border-radius:3px; overflow:hidden; margin-top:7px; }
.bar > i { display:block; height:100%; background:var(--accent); }
.halt { background:#20120f; border:1px solid #5a231b; border-left:3px solid var(--bad);
  padding:16px 18px; border-radius:8px; }
.halt b { color:var(--bad); }
.mono { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:13px; }
footer { margin-top:52px; padding-top:20px; border-top:1px solid var(--line);
  color:var(--muted); font-size:13px; }
"""


def _rs(paise: int) -> str:
    neg = paise < 0
    s = f"Rs.{abs(paise) / 100:,.0f}"
    return ("-" + s) if neg else s


def _pct(x: float) -> str:
    return f"{x:+.1%}"


def render(data: dict) -> str:
    m = data["metrics"]
    rates = m["recovery_rates"]
    money = m["money_paise"]
    lift = rates["lift"]
    ext = data["extraction"]

    sig = lift["significant"]
    lift_cls = "good" if (sig and lift["point"] > 0) else ("muted" if not sig else "bad")

    ci = money.get("incremental_ci")
    ci_txt = f"95% CI [{_rs(ci[0])}, {_rs(ci[1])}]" if ci else "no control arm"

    parts: list[str] = []
    A = parts.append

    A(f"<!-- generated by recouper.report -->")
    A(f"<style>{CSS}</style>")
    A('<div class="wrap">')
    A("<h1>Recouper &mdash; batch report</h1>")
    A(f'<p class="sub">Seed {data["seed"]} &middot; '
      f'{data["corpus"]["total_records"]} synthetic records &middot; '
      f'{ext["total_cases"]} cases extracted</p>')

    A('<div class="caveat"><b>All recovery outcomes are simulated.</b> '
      'Test-mode APIs cannot make a synthetic customer decide to pay, so the '
      'final outcome is drawn from the documented model in '
      '<span class="mono">outcomes/simulate.py</span>. The contribution is the '
      'measurement framework and the bounded execution &mdash; not the absolute '
      'rupee figure.</div>')

    # --- headline ---------------------------------------------------------
    A("<h2>Did we actually recover anything?</h2>")
    A('<div class="grid">')
    A(_card("Treated recovery", f'{rates["treated"]:.1%}',
            f'{m["arms"]["treated"]} cases worked'))
    A(_card("Control self-recovery", f'{rates["control_self_recovery"]:.1%}',
            f'{m["arms"]["control"]} cases untouched &mdash; these paid with no '
            f'help from us', cls="muted"))
    A(_card("Incremental lift", _pct(lift["point"]),
            f'95% CI [{lift["ci_low"]:+.1%}, {lift["ci_high"]:+.1%}]<br>'
            + ('<span class="tag yes">significant</span>' if sig
               else '<span class="tag no">not significant &mdash; CI contains zero</span>'),
            cls=lift_cls, hero=True))
    A("</div>")

    A("<h2>Money</h2>")
    A('<div class="grid">')
    A(_card("Gross recovered", _rs(money["gross_recovered"]),
            "<b>Inflated.</b> Includes customers who would have paid anyway. "
            "Not a claim of impact.", cls="muted"))
    A(_card("Incremental recovered", _rs(money["incremental_recovered"]),
            ci_txt + " &mdash; the honest number", hero=True,
            cls="good" if money["incremental_recovered"] > 0 else "bad"))
    if money.get("overstatement_factor"):
        A(_card("Overstatement", f'{money["overstatement_factor"]:.1f}&times;',
                "How much larger the gross claim is than the measured effect",
                cls="bad"))
    A("</div>")

    # --- per cohort -------------------------------------------------------
    A("<h2>Where the effect actually is</h2>")
    A("<table><tr><th>Cohort</th><th class='num'>n (T/C)</th>"
      "<th class='num'>Treated</th><th class='num'>Control</th>"
      "<th class='num'>Lift</th><th>95% CI</th><th>Verdict</th></tr>")
    for name, v in sorted(
        m["per_class"].items(),
        key=lambda kv: -(kv[1].get("lift", {}).get("point", -9)),
    ):
        if "lift" not in v:
            A(f"<tr><td>{html.escape(name)}</td>"
              f"<td class='num'>{v['n_treated']}/{v['n_control']}</td>"
              f"<td colspan='4' style='color:var(--muted)'>{html.escape(v['note'])}</td>"
              f"<td><span class='tag no'>no estimate</span></td></tr>")
            continue
        l = v["lift"]
        tag = ('<span class="tag yes">significant</span>' if l["significant"]
               else '<span class="tag no">inconclusive</span>')
        A(f"<tr><td>{html.escape(name)}</td>"
          f"<td class='num'>{v['n_treated']}/{v['n_control']}</td>"
          f"<td class='num'>{v['treated_rate']:.1%}</td>"
          f"<td class='num'>{v['control_rate']:.1%}</td>"
          f"<td class='num' style='color:{'var(--good)' if l['point']>0 else 'var(--bad)'}'>"
          f"{l['point']:+.1%}</td>"
          f"<td class='mono'>[{l['ci_low']:+.1%}, {l['ci_high']:+.1%}]</td>"
          f"<td>{tag}</td></tr>")
    A("</table>")

    # --- bounds -----------------------------------------------------------
    A("<h2>The bounds that bound</h2>")
    denials = data.get("denials", {})
    if denials:
        top = max(denials.values())
        A("<table><tr><th>Policy rule</th><th class='num'>Actions blocked</th>"
          "<th style='width:38%'></th></tr>")
        for rule, n in denials.items():
            A(f"<tr><td class='mono'>{html.escape(rule)}</td>"
              f"<td class='num'>{n}</td>"
              f"<td><div class='bar'><i style='width:{100*n/top:.0f}%'></i></div></td></tr>")
        A("</table>")
    else:
        A("<p class='sub'>No denials recorded &mdash; check the policy engine is wired in.</p>")

    act = m["activity"]
    fp = m["false_positives"]
    A('<div class="grid" style="margin-top:14px">')
    A(_card("Contacts sent", str(act["contacts_sent"]), "after policy gating"))
    A(_card("Retries attempted", str(act["retries_attempted"]),
            "only where a reusable mandate existed"))
    A(_card("Escalated to human", str(act["escalated_to_human"]),
            "above the Rs.50,000 ceiling, or unclassifiable"))
    A(_card("Wasted contacts", str(fp["wasted_contacts"]),
            "customers who would have paid anyway &mdash; we cannot tell "
            "<i>which</i>, only how many", cls="bad"))
    A("</div>")

    # --- failure ----------------------------------------------------------
    if data.get("halted"):
        A("<h2>Batch halted</h2>")
        A(f'<div class="halt"><b>Circuit breaker tripped.</b> '
          f'{html.escape(str(data.get("halt_reason","")))}<br><br>'
          f'{len(data.get("dead_letters", []))} cases parked in the dead letter '
          f'queue with full context. No duplicate customer contacts were sent &mdash; '
          f'idempotency keys are derived from (case, action, attempt). '
          f'Resume is a manual operation; the breaker does not self-heal.</div>')

    A('<footer>Generated by <span class="mono">recouper.report</span>. '
      'Every recovery outcome is simulated under an explicit, inspectable '
      'model. No real customer data was used and no message was ever sent.'
      '</footer>')
    A("</div>")
    return "\n".join(parts)


def _card(label: str, value: str, note: str = "", *, cls: str = "", hero: bool = False) -> str:
    return (
        f'<div class="card{" hero" if hero else ""}">'
        f'<div class="label">{label}</div>'
        f'<div class="value {cls}">{value}</div>'
        + (f'<div class="note">{note}</div>' if note else "")
        + "</div>"
    )


def write_report(result_json: dict, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "<!doctype html><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Recouper - batch report</title>" + render(result_json),
        encoding="utf-8",
    )
    return p


if __name__ == "__main__":  # pragma: no cover
    import sys

    src = sys.argv[1] if len(sys.argv) > 1 else "runs/result_seed42.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "runs/report.html"
    print(write_report(json.loads(Path(src).read_text(encoding="utf-8")), out))
